"""tests/test_fusion_blocks.py — Unit tests for fusion/blocks/ and fusion/stems/."""
from __future__ import annotations

def test_modality_stem_output_shape(): ...
def test_deep_fusion_block_output_shape(): ...
def test_light_fusion_block_output_shape(): ...
def test_deep_fusion_block_gradients(): ...
def test_light_fusion_block_gradients(): ...
def test_cross_attention_output_shape(): ...
def test_topology_constructor_light_branch(): ...
def test_topology_constructor_deep_branch(): ...
def test_topology_constructor_both_branch(): ...
def test_topology_blend_weights_applied(): ...
