"""tests/test_discriminator.py — Unit tests for gan/discriminator/."""
from __future__ import annotations

def test_fusion_quality_critic_output_shape(): ...
def test_fusion_quality_critic_range(): ...       # Qt ∈ [0, 1]
def test_latency_critic_output_shape(): ...
def test_latency_critic_descriptor_shape(): ...
def test_task_critic_output_shape(): ...
def test_discriminator_forward_all_critics(): ...
def test_discriminator_loss_scalar(): ...
def test_discriminator_gradients_flow(): ...
