"""tests/test_encoder.py — Unit tests for shared/encoder/."""
from __future__ import annotations

def test_multimodal_encoder_output_shapes(): ...
def test_confidence_estimator_range(): ...
def test_encoder_gradients_flow(): ...
def test_encoder_single_channel_adaptation(): ...
