"""tests/test_ppo_agent.py — Unit tests for rl/."""
from __future__ import annotations

def test_actor_output_shapes(): ...
def test_actor_log_prob_shape(): ...
def test_critic_output_shape(): ...
def test_ppo_agent_act_dict_keys(): ...
def test_ppo_agent_evaluate_dict_keys(): ...
def test_rollout_buffer_add_and_full(): ...
def test_rollout_buffer_gae_computation(): ...
def test_rollout_buffer_minibatches_shapes(): ...
def test_ppo_update_returns_metrics(): ...
def test_scene_graph_network_output_shape(): ...
def test_meta_fusion_bank_output_shape(): ...
def test_state_builder_output_shape(): ...
