"""tests/test_losses.py — Unit tests for shared/losses/."""
from __future__ import annotations

def test_adversarial_loss_bce(): ...
def test_adversarial_loss_hinge(): ...
def test_fusion_loss_ssim_range(): ...
def test_fusion_loss_perceptual(): ...
def test_latency_loss_scalar(): ...
def test_task_loss_range(): ...
def test_generator_loss_engine_keys(): ...
def test_generator_loss_engine_weighted_sum(): ...
def test_loss_gradients_flow_to_generator(): ...
